# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MPCA Data Guide
tagline:          'Community data guide'
description:      'A community organized guide to finding data'
url:              https://MPCA-data.github.io/Data-Guide/

author:
  name:           'MPCA'
  url:            https://twitter.com/mnpca

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mpca-data/Data-Guide
